#!/usr/bin/env bash
set -e

function echo_stderr {
  1>&2 echo "${1}"
}

function checkprog {
  command -v "${1}" > /dev/null 2>&1 || { echo_stderr "ERROR: Pre-commit dependency ${1} not found in PATH, exiting"; exit 1; }
}

echo_stderr "#==============================================================================="
echo_stderr "# pre-commit START"
echo_stderr "#==============================================================================="

declare -a DEPENDENCIES=( "black" "isort" )

echo_stderr "INFO: Checking pre-commit dependencies..."

for PROG in "${DEPENDENCIES[@]}"; do
  checkprog "${PROG}"
done

if git rev-parse --verify HEAD > /dev/null 2>&1; then
  COMPARISON_REVISION=HEAD
else
  COMPARISON_REVISION=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

for FILE in $(git diff --name-only --cached "${COMPARISON_REVISION}"); do
  if [[ "${FILE}" == *.py ]]; then
    echo_stderr "INFO: Running tasks on Python file ${FILE}"
    isort "${FILE}"
    black --line-length 80 --quiet "${FILE}" 2>/dev/null
  else
    echo_stderr "INFO: ${FILE} isn't a Python file, so not doing anything to it"
  fi
done

echo_stderr "#==============================================================================="
echo_stderr "# pre-commit END"
echo_stderr "#==============================================================================="
