name: 'Python Unit Tests'
on:
  push:
    branches: [ 'feature/*', 'bugfix/*', 'hotfix/*' ]
  pull_request:
    branches: [ 'master' ]

jobs:
    unit_tests:
      name: 'Unit Tests'
      runs-on: 'ubuntu-latest'
      steps:
        - name: 'Checkout'
          uses: actions/checkout@v2
          id: 'checkout'
        - name: 'Run Tests'
          uses: ./.github/actions/unittest
          id: 'run_tests'
